global using Manual_Ocelot.Configurations;
global using Manual_Ocelot.Entities;
global using Manual_Ocelot.Middlewares;
global using Manual_Ocelot.Services.GatewayServices;
global using Manual_Ocelot.Services.TokenValidationServices;
global using Microsoft.EntityFrameworkCore;
global using System.Net;
global using System.Text;
global using Manual_Ocelot.Constants;
global using Newtonsoft.Json;
global using System.Collections.Concurrent;
global using Route = Manual_Ocelot.Configurations.Route;
global using System.Security.Claims;
